# Sometimes it's a README fix, or something like that - which isn't relevant for
# including in a project's CHANGELOG for example
declared_trivial = github.pr_title.include? '#trivial'

# Make it more obvious that a PR is a work in progress and shouldn't be merged yet
warn('PR is classed as Work in Progress') if github.pr_title.include? '[WIP]'

# Warn when there is a big pr
warn("Big PR") if git.lines_of_code > 500

# Don't let testing shortcuts get into master by accident
fail('describe left in tests') if `grep -r fdescribe specs/ `.length > 1
fail('fit left in tests') if `grep -r fit specs/ `.length > 1
fail('You forgot to update the checklist! Plese update it according to your pr, otherwise we can introduce bugs') if !github.pr_body.include? "[x]"

# Run SwiftLint
swiftlint.config_file = '.swiftlint.yml'
swiftlint.lint_files

# What changed?
has_lib_changes = !git.modified_files.grep(/Freshly/).empty?
has_test_changes = !git.modified_files.grep(/FreshlyTests/).empty?
has_changelog_changes = git.modified_files.include?("CHANGELOG.md")
has_performance_issue = !git.modified_files.grep(/Freshly/.performance/).empty?

# You did not add a milestone
fail('All PRs should have a milestone attached.') if github.pr_json['milestone'].nil?

# Performance
if has_performance_issue
  warn('Not performing at 60FPS')
end

# You did not assign yourself as assignee
fail('All PRs should have a assignee attached.') if github.pr_json['assignee'].nil?

# You did not add a label  to the pr
fail('All PRs should have a label.') if github.pr_labels.empty?

# You've made changes to lib, but didn't write any tests?
if has_lib_changes && !has_test_changes
  warn("There are code changes, but no corresponding tests. "\
       "Please include tests if this PR introduces any modifications in "\
       "Freshly's behavior.",
       :sticky => false)
end

# Code coverage
# Disabling for now, since it's broken when you upgrade Fastlane. I created this ticket to update this: https://freshly.atlassian.net/browse/IOS-7315
# SCHEME = 'Freshly Dev'
# xcov.report(
#    scheme: SCHEME,
#    workspace: 'Freshly.xcworkspace',
#    only_project_targets: true,
#    minimum_coverage_percentage: 51.0,
# )

changelog.check

